/* Tin Soldiers: Nova - data-driven tuning: factions, roster, buildings, upgrades, damage rules. */
(function () {
  "use strict";
  const N = (globalThis.NOVA = globalThis.NOVA || {});

  N.VERSION = "0.2.0-upgrade";
  N.TITLE = "Tin Soldiers: Nova - Full Team Battles";
  N.SAVE_NS = "tinsoldiers-nova-upgrade:v1";
  N.MAX_PLAYERS = 6;
  N.TICK = 0.05; // 20 Hz fixed simulation
  N.RESOURCE = "Aether";
  N.MAX_SUPPLY = 100;
  N.START_RES = 400;
  N.START_WORKERS = 5;
  N.MATCH_LIMIT = 45 * 60; // seconds; see README "Finite outcomes"
  N.OBJ_TARGET = 900; // capture-mode score to win
  N.OBJ_INCOME = 1.5; // aether/sec per held point (both modes)
  N.BUILD_RANGE = 26; // structures must be this close to a finished own structure
  N.BUILD_GAP = 1; // tiles of free space required between structures

  // Weapon kinds. Kinds in NO_AIR can NEVER hit airborne targets even if a data row says air:true.
  N.NO_AIR = ["bullet", "spine", "claw", "cannon", "shell", "acid"];
  // Kind vs target armor type multipliers (separate from armor value, target eligibility and range).
  N.KIND_VS = {
    bullet: { structure: 0.6 },
    spine: { structure: 0.6 },
    claw: { structure: 0.85 },
    rocket: { light: 0.6 },
    acid: { light: 0.9 },
    cannon: {},
    shell: { structure: 1.3, light: 1.1 },
    energy: {},
    beam: {},
    lance: { light: 0.6 },
    plasma: { structure: 1.2 },
    spore: { structure: 0.5 },
    arc: {},
  };
  N.ARMOR_MIN = 0.15; // damage never falls below 15% of pre-armor damage
  N.COVER = { light: 0.25, heavy: 0.4 }; // damage reduction when shot from the covered side
  N.COVER_ARC = 70; // degrees either side of the cover direction that are "covered"
  N.FLANK_ARC = 120; // shot from more than this many degrees off the target's facing = flanked
  N.FLANK_BONUS = 1.2;

  N.ROLES = [
    "worker",
    "trooper",
    "raider",
    "lancer",
    "skyhunter",
    "walker",
    "artillery",
    "flyer",
    "support",
    "heavy",
  ];
  N.BROLES = [
    "hq",
    "supply",
    "dropoff",
    "barracks",
    "factory",
    "airfield",
    "lab",
    "turret",
    "aaturret",
  ];
  N.ROLE_LABEL = {
    worker: "Worker",
    trooper: "Line infantry",
    raider: "Scout/raider",
    lancer: "Anti-armor",
    skyhunter: "Anti-air",
    walker: "Armored mech",
    artillery: "Artillery",
    flyer: "Flyer",
    support: "Support",
    heavy: "Heavy",
  };
  N.ABIL_CD = 100;

  const BASE_UNIT = {
    radius: 0.4,
    speed: 3,
    sight: 10,
    atype: "light",
    armor: 0,
    shield: 0,
    shieldRegen: 0,
    supply: 1,
    air: false,
    inf: false,
    weapons: [],
    hp: 50,
    cost: 50,
    time: 10,
    regen: 0,
    hover: false,
    heal: null,
  };
  const BASE_W = {
    kind: "bullet",
    dmg: 5,
    pen: 0,
    range: 6,
    cd: 1,
    air: false,
    ground: true,
    splash: 0,
    delay: 0,
    min: 0,
    name: "Weapon",
  };
  const W = (o) => Object.assign({}, BASE_W, o);
  const U = (role, name, prod, req, o) =>
    Object.assign(
      {},
      BASE_UNIT,
      { role, name, prod, req: req || [], kind: "unit" },
      o,
    );
  const B = (role, name, o) =>
    Object.assign(
      {
        role,
        name,
        kind: "building",
        size: 3,
        cost: 100,
        time: 20,
        hp: 400,
        armor: 3,
        atype: "structure",
        sight: 8,
        supply: 0,
        req: [],
        dropoff: false,
        prod: [],
        weapons: [],
      },
      o,
    );

  function buildings(name, m) {
    // m: faction structure modifiers {cost, hp, time, ...}
    const c = (v) => Math.round(v * m.cost),
      h = (v) => Math.round(v * m.hp),
      t = (v) => Math.round(v * m.time);
    return {
      hq: B("hq", name.hq, {
        size: 4,
        cost: c(400),
        time: t(60),
        hp: h(1600),
        armor: 4,
        sight: 13,
        supply: 10,
        dropoff: true,
        req: ["barracks"],
        prod: ["worker"],
        desc: "Command hub. Drops off Aether, trains workers, +10 supply. Losing every structure loses the match.",
      }),
      supply: B("supply", name.supply, {
        size: 2,
        cost: c(80),
        time: t(18),
        hp: h(320),
        supply: 8,
        desc: "+8 supply. Build more before you hit the cap.",
      }),
      dropoff: B("dropoff", name.dropoff, {
        size: 3,
        cost: c(100),
        time: t(22),
        hp: h(420),
        dropoff: true,
        desc: "Forward Aether drop-off. Build near a distant deposit to shorten worker trips.",
      }),
      barracks: B("barracks", name.barracks, {
        size: 3,
        cost: c(150),
        time: t(28),
        hp: h(650),
        prod: ["trooper", "raider", "lancer", "skyhunter", "support"],
        desc: "Trains infantry, raiders, anti-armor and anti-air. Unlocks the tech tree.",
      }),
      factory: B("factory", name.factory, {
        size: 4,
        cost: c(250),
        time: t(38),
        hp: h(850),
        req: ["barracks"],
        prod: ["walker", "artillery", "heavy"],
        desc: "Trains armored mechs, artillery and heavy units (artillery/heavy also need the research building).",
      }),
      airfield: B("airfield", name.airfield, {
        size: 3,
        cost: c(260),
        time: t(38),
        hp: h(700),
        req: ["factory"],
        prod: ["flyer"],
        desc: "Trains flyers. Flyers ignore terrain and can only be hit by anti-air weapons.",
      }),
      lab: B("lab", name.lab, {
        size: 3,
        cost: c(200),
        time: t(34),
        hp: h(600),
        req: ["barracks"],
        prod: [],
        research: true,
        desc: "Research upgrades. Unlocks support, artillery, heavy units and the faction ability.",
      }),
      turret: B("turret", name.turret, {
        size: 2,
        cost: c(120),
        time: t(22),
        hp: h(380),
        armor: 5,
        sight: 11,
        req: ["barracks"],
        weapons: [W(m.turretW)],
        desc: "Ground-only defensive turret. Cannot shoot air.",
      }),
      aaturret: B("aaturret", name.aaturret, {
        size: 2,
        cost: c(140),
        time: t(24),
        hp: h(320),
        armor: 3,
        sight: 12,
        req: ["barracks"],
        weapons: [W(m.aaW)],
        desc: "Anti-air-only defensive battery. Cannot shoot ground targets.",
      }),
    };
  }

  const UPG = (f) => ({
    dmg1: {
      name: "Weapon Tuning I",
      cost: 150,
      time: 40,
      req: [],
      desc: "+12% weapon damage for all units and turrets.",
    },
    dmg2: {
      name: "Weapon Tuning II",
      cost: 250,
      time: 55,
      req: ["dmg1"],
      desc: "Another +12% weapon damage.",
    },
    armor1: {
      name: "Plating I",
      cost: 150,
      time: 40,
      req: [],
      desc: "+1 armor on all units and structures.",
    },
    armor2: {
      name: "Plating II",
      cost: 250,
      time: 55,
      req: ["armor1"],
      desc: "Another +1 armor.",
    },
    special: Object.assign({ cost: 200, time: 50, req: [] }, f),
  });

  const F = {};

  /* ------------------------------------------------------------------ Argent Vanguard */
  F.vanguard = {
    id: "vanguard",
    name: "Argent Vanguard",
    short: "Vanguard",
    color: "#8fa3b5",
    accent: "#ff9f3c",
    tagline: "Armored expeditionary force",
    lore: "A relief fleet from a dying orbital republic. Drop-pods, walker mechs and disciplined firepower: tough, expensive and methodical.",
    strengths:
      "Highest armor and structure durability, strong turrets, field medics. Weak to mass anti-armor and to being out-produced early.",
    traits: ["Structures +20% hull", "Sturdy turrets", "Orbital Lance ability"],
    units: {
      worker: U("worker", "Sapper", "hq", [], {
        cost: 45,
        time: 9,
        hp: 45,
        speed: 3.2,
        radius: 0.38,
        inf: true,
        note: "Builds, repairs and mines Aether.",
      }),
      trooper: U("trooper", "Rifleman", "barracks", [], {
        cost: 55,
        time: 12,
        hp: 65,
        armor: 1,
        speed: 3.2,
        inf: true,
        weapons: [
          W({
            name: "Pulse Rifle",
            kind: "bullet",
            dmg: 7,
            pen: 0,
            range: 7,
            cd: 0.8,
          }),
        ],
        strong: "Infantry, workers, cost-efficient vs light targets",
        weak: "Bullets barely scratch mechs; cannot hit air",
        note: "Ordinary bullets: cannot target air, heavily resisted by armor.",
      }),
      raider: U("raider", "Rover", "barracks", [], {
        cost: 75,
        time: 14,
        hp: 75,
        armor: 1,
        atype: "medium",
        speed: 5.2,
        sight: 13,
        radius: 0.5,
        weapons: [
          W({
            name: "Rover Gun",
            kind: "bullet",
            dmg: 5,
            pen: 0,
            range: 6,
            cd: 0.5,
          }),
        ],
        strong: "Scouting, harassing workers, artillery",
        weak: "Anything armored; lancers",
        note: "Fast scout car.",
      }),
      lancer: U("lancer", "Lancer", "barracks", [], {
        cost: 85,
        time: 16,
        hp: 60,
        armor: 1,
        speed: 3,
        inf: true,
        weapons: [
          W({
            name: "Lance Rocket",
            kind: "rocket",
            dmg: 34,
            pen: 9,
            range: 8,
            cd: 2.2,
          }),
        ],
        strong: "Armored mechs, heavies, structures",
        weak: "Rifle infantry, raiders; cannot hit air",
        note: "Armor-piercing rockets, ground only.",
      }),
      skyhunter: U("skyhunter", "Skyhunter", "barracks", [], {
        cost: 80,
        time: 15,
        hp: 55,
        armor: 1,
        speed: 3,
        inf: true,
        weapons: [
          W({
            name: "Flak Missile",
            kind: "rocket",
            dmg: 15,
            pen: 4,
            range: 10,
            cd: 1.5,
            air: true,
            ground: false,
          }),
        ],
        strong: "All flyers",
        weak: "Cannot attack ground at all",
        note: "Dedicated anti-air missiles: air targets only.",
      }),
      walker: U("walker", "Bulwark Walker", "factory", [], {
        cost: 220,
        time: 30,
        supply: 3,
        hp: 280,
        armor: 6,
        atype: "heavy",
        speed: 2.6,
        radius: 0.85,
        sight: 11,
        weapons: [
          W({
            name: "Autocannon",
            kind: "cannon",
            dmg: 24,
            pen: 5,
            range: 8,
            cd: 1.3,
          }),
        ],
        strong: "Riflemen, raiders, structures",
        weak: "Lancers, artillery; cannot hit air",
        note: "Heavy armor 6 shrugs off ordinary gunfire.",
      }),
      artillery: U("artillery", "Hammer Howitzer", "factory", ["lab"], {
        cost: 200,
        time: 28,
        supply: 3,
        hp: 95,
        armor: 2,
        atype: "medium",
        speed: 2.2,
        radius: 0.7,
        sight: 10,
        weapons: [
          W({
            name: "Howitzer",
            kind: "shell",
            dmg: 38,
            pen: 3,
            range: 20,
            min: 6,
            cd: 4,
            splash: 2.5,
            delay: 1.5,
          }),
        ],
        strong: "Clumped infantry, structures, siege",
        weak: "Anything that closes in; slow shells miss movers",
        note: "Long-range splash, minimum range 6, shells take 1.5s to land.",
      }),
      flyer: U("flyer", "Talon Gunship", "airfield", [], {
        cost: 210,
        time: 30,
        supply: 3,
        hp: 150,
        armor: 2,
        atype: "air",
        speed: 4.5,
        radius: 0.7,
        air: true,
        sight: 11,
        weapons: [
          W({
            name: "Rocket Pods",
            kind: "rocket",
            dmg: 11,
            pen: 3,
            range: 7,
            cd: 0.6,
          }),
        ],
        strong: "Ground infantry, artillery, workers",
        weak: "Skyhunters and AA turrets; cannot hit air",
        note: "Flying. Only anti-air weapons can hit it. Attacks ground only.",
      }),
      support: U("support", "Field Medic", "barracks", ["lab"], {
        cost: 70,
        time: 14,
        hp: 60,
        speed: 3.2,
        inf: true,
        heal: { rate: 9, range: 5, aura: false, shield: 0 },
        weapons: [],
        strong: "Sustains a squad",
        weak: "Unarmed",
        note: "Auto-heals one wounded ally at a time (9 hp/s).",
      }),
      heavy: U("heavy", "Titan", "factory", ["lab"], {
        cost: 460,
        time: 50,
        supply: 6,
        hp: 750,
        armor: 9,
        atype: "heavy",
        speed: 2.2,
        radius: 1.15,
        sight: 12,
        weapons: [
          W({
            name: "Twin Cannon",
            kind: "cannon",
            dmg: 32,
            pen: 7,
            range: 9.5,
            cd: 1.1,
          }),
        ],
        strong: "Nearly everything on the ground",
        weak: "Lancers en masse, air, artillery; cannot hit air",
        note: "Armor 9: only dedicated anti-armor weapons hurt it.",
      }),
    },
    buildings: buildings(
      {
        hq: "Command Bastion",
        supply: "Supply Cache",
        dropoff: "Aether Refinery",
        barracks: "Drop Bay",
        factory: "Mech Foundry",
        airfield: "Skydock",
        lab: "Research Array",
        turret: "Bulwark Turret",
        aaturret: "Flak Battery",
      },
      {
        cost: 1,
        hp: 1.2,
        time: 1,
        turretW: {
          name: "Bulwark Cannon",
          kind: "cannon",
          dmg: 16,
          pen: 4,
          range: 9,
          cd: 1,
        },
        aaW: {
          name: "Flak Missile",
          kind: "rocket",
          dmg: 15,
          pen: 4,
          range: 11,
          cd: 1.3,
          air: true,
          ground: false,
        },
      },
    ),
    upgrades: UPG({
      name: "Ion Capacitors",
      desc: "+1.5 weapon range on all units.",
      effect: "range",
    }),
    ability: {
      name: "Orbital Lance",
      desc: "Calls a lance strike: 150 damage in radius 4 after a 2s delay (structures take half). Needs the research building.",
      radius: 4,
      dmg: 150,
      delay: 2,
      cd: 100,
      target: "ground",
    },
    power: {
      id: "droppod",
      name: "Drop-Pod Salvo",
      short: "Drop Pod",
      key: "G",
      cost: 220,
      cd: 110,
      delay: 4,
      radius: 2.5,
      crush: 45,
      spawn: ["trooper", "trooper", "trooper", "lancer"],
      target: "ground",
      tint: 0xff9f3c,
      desc: "Marks a landing zone. After a 4s telegraph a pod lands, crushing enemy ground units in radius 2.5 for 45 damage and deploying 3 Riflemen + 1 Lancer for you. Costs 220 Aether up front (units that do not fit under your supply cap are refunded at their unit price). Needs the research building, a landing zone your team can see, and at least 10 tiles from any enemy structure. Cooldown 110s. Counterplay: the ring is visible to everyone; move out of it or kill the fresh, unsupported squad.",
    },
    mods: { regen: 0, autoGrow: 0, prodTime: 1, buildBonusHp: 1.2 },
  };

  /* ------------------------------------------------------------------ Vhaal Brood */
  F.brood = {
    id: "brood",
    name: "Vhaal Brood",
    short: "Brood",
    color: "#8bd45a",
    accent: "#c94cff",
    tagline: "Biological alien hive",
    lore: "An evolving swarm that treats worlds as nurseries. Cheap, fast, self-healing organisms that grow their own structures.",
    strengths:
      "Cheap and fast production, regeneration, buildings grow on their own, quick to expand. Weak armor and range.",
    traits: ["Units regenerate", "Structures self-grow", "Bloom Pulse ability"],
    units: {
      worker: U("worker", "Drone", "hq", [], {
        cost: 40,
        time: 8,
        hp: 35,
        speed: 3.6,
        radius: 0.34,
        inf: true,
        note: "Builds, repairs and mines Aether. Cheaper than other workers.",
      }),
      trooper: U("trooper", "Spinecaster", "barracks", [], {
        cost: 45,
        time: 10,
        hp: 52,
        speed: 3.6,
        inf: true,
        weapons: [
          W({
            name: "Spine Volley",
            kind: "spine",
            dmg: 6,
            pen: 0,
            range: 6.5,
            cd: 0.7,
          }),
        ],
        strong: "Massed vs infantry, workers",
        weak: "Armor shrugs spines; cannot hit air",
        note: "Spines behave like bullets: no air targeting, poor vs armor.",
      }),
      raider: U("raider", "Skitterer", "barracks", [], {
        cost: 60,
        time: 12,
        hp: 42,
        speed: 6.2,
        sight: 13,
        radius: 0.36,
        inf: true,
        weapons: [
          W({
            name: "Rending Claws",
            kind: "claw",
            dmg: 8,
            pen: 1,
            range: 1.6,
            cd: 0.5,
          }),
        ],
        strong: "Scouting, workers, artillery",
        weak: "Fragile; anything ranged",
        note: "Melee raider. Fast.",
      }),
      lancer: U("lancer", "Acid Spitter", "barracks", [], {
        cost: 75,
        time: 15,
        hp: 50,
        speed: 3.3,
        inf: true,
        weapons: [
          W({
            name: "Corrosive Acid",
            kind: "acid",
            dmg: 30,
            pen: 8,
            range: 8,
            cd: 2,
          }),
        ],
        strong: "Mechs, heavies, structures",
        weak: "Anything that closes in; cannot hit air",
        note: "Acid melts armor. Ground only.",
      }),
      skyhunter: U("skyhunter", "Spore Launcher", "barracks", [], {
        cost: 70,
        time: 14,
        hp: 50,
        speed: 3.2,
        inf: true,
        weapons: [
          W({
            name: "Spore Burst",
            kind: "spore",
            dmg: 11,
            pen: 3,
            range: 10,
            cd: 1.3,
            splash: 1.5,
            air: true,
            ground: false,
          }),
        ],
        strong: "Flyer swarms (splash)",
        weak: "Cannot attack ground",
        note: "Spore clouds hit air only, with a small splash.",
      }),
      walker: U("walker", "Ravager", "factory", [], {
        cost: 220,
        time: 28,
        supply: 3,
        hp: 250,
        armor: 5,
        atype: "heavy",
        speed: 3.2,
        radius: 0.9,
        sight: 11,
        weapons: [
          W({
            name: "Scything Claws",
            kind: "claw",
            dmg: 30,
            pen: 6,
            range: 2.6,
            cd: 1,
          }),
        ],
        strong: "Armor & structures in melee",
        weak: "Kited by ranged units; cannot hit air",
        note: "Melee brute with armor 5 that pierces armor 6.",
      }),
      artillery: U("artillery", "Bile Lobber", "factory", ["lab"], {
        cost: 185,
        time: 28,
        supply: 3,
        hp: 80,
        armor: 1,
        atype: "medium",
        speed: 2.4,
        radius: 0.7,
        weapons: [
          W({
            name: "Bile Mortar",
            kind: "acid",
            dmg: 34,
            pen: 3,
            range: 18,
            min: 5,
            cd: 4.2,
            splash: 3,
            delay: 1.7,
          }),
        ],
        strong: "Infantry blobs, structures",
        weak: "Anything that closes in",
        note: "Range 18, min range 5, splash 3.",
      }),
      flyer: U("flyer", "Screecher", "airfield", [], {
        cost: 190,
        time: 28,
        supply: 3,
        hp: 95,
        armor: 0,
        atype: "air",
        speed: 5.4,
        radius: 0.6,
        air: true,
        sight: 11,
        weapons: [
          W({
            name: "Shriek Spores",
            kind: "spore",
            dmg: 8,
            pen: 2,
            range: 7,
            cd: 0.7,
            air: true,
            ground: true,
          }),
        ],
        strong: "Air-to-air, harassment",
        weak: "Fragile; spore launchers",
        note: "Fast flyer. Spores can hit both air and ground.",
      }),
      support: U("support", "Mender", "barracks", ["lab"], {
        cost: 60,
        time: 12,
        hp: 60,
        speed: 3.4,
        inf: true,
        heal: { rate: 4, range: 5, aura: true, shield: 0 },
        weapons: [],
        strong: "Sustains a swarm",
        weak: "Unarmed",
        note: "Heals 4 hp/s to every ally within 5.",
      }),
      heavy: U("heavy", "Leviathan", "factory", ["lab"], {
        cost: 440,
        time: 50,
        supply: 6,
        hp: 620,
        armor: 6,
        atype: "heavy",
        speed: 2.4,
        radius: 1.25,
        sight: 12,
        regen: 1.5,
        weapons: [
          W({
            name: "Bile Cannon",
            kind: "acid",
            dmg: 42,
            pen: 7,
            range: 10,
            cd: 1.9,
            splash: 2,
          }),
        ],
        strong: "Ground armies, structures",
        weak: "Mass air, lancer swarms; cannot hit air",
        note: "Regenerates rapidly. Ground only.",
      }),
    },
    buildings: buildings(
      {
        hq: "Brood Heart",
        supply: "Spawning Sac",
        dropoff: "Digester",
        barracks: "Warren",
        factory: "Carapace Pit",
        airfield: "Aerie",
        lab: "Evolution Spire",
        turret: "Spine Tower",
        aaturret: "Spore Tower",
      },
      {
        cost: 0.9,
        hp: 0.85,
        time: 1,
        turretW: {
          name: "Spine Barrage",
          kind: "spine",
          dmg: 13,
          pen: 3,
          range: 9,
          cd: 1,
        },
        aaW: {
          name: "Spore Burst",
          kind: "spore",
          dmg: 14,
          pen: 3,
          range: 11,
          cd: 1.3,
          splash: 1.5,
          air: true,
          ground: false,
        },
      },
    ),
    upgrades: UPG({
      name: "Metabolic Surge",
      desc: "Triples unit regeneration.",
      effect: "regen",
    }),
    ability: {
      name: "Bloom Pulse",
      desc: "Releases a healing spore burst: allies within radius 7 recover 80 hp. Needs the research building.",
      radius: 7,
      heal: 80,
      delay: 0.5,
      cd: 80,
      target: "ground",
    },
    power: {
      id: "frenzy",
      name: "Pheromone Frenzy",
      short: "Frenzy",
      key: "G",
      cost: 60,
      cd: 75,
      delay: 0,
      radius: 8,
      duration: 8,
      spent: 6,
      speedMul: 1.45,
      rateMul: 1.4,
      spentSpeed: 0.7,
      spentRate: 0.75,
      target: "ground",
      tint: 0xc94cff,
      desc: "Whips every allied unit within radius 8 of the target (including your teammates' units) into a frenzy for 8s: +45% move speed and +40% attack rate. Afterwards they are exhausted for 6s: -30% move speed and -25% attack rate. Costs 60 Aether, cooldown 75s. Needs the research building and a target area your team can see. Counterplay: retreat and kite through the exhaustion window; frenzied units glow, so you can see when to fall back.",
    },
    mods: { regen: 0.5, autoGrow: 0.45, prodTime: 0.9, buildBonusHp: 1 },
  };

  /* ------------------------------------------------------------------ Aeon Lattice */
  F.lattice = {
    id: "lattice",
    name: "Aeon Lattice",
    short: "Lattice",
    color: "#f0d27a",
    accent: "#39e6d6",
    tagline: "Ancient machine civilization",
    lore: "Dormant war-engines of a vanished empire, woken by the crash. Hovering, shielded, precise and costly.",
    strengths:
      "Regenerating energy shields, hover units ignore rough ground, precise beam weapons. Expensive, lightly armored hulls.",
    traits: [
      "Regenerating shields",
      "Hover ignores slow terrain",
      "Aegis Field ability",
    ],
    units: {
      worker: U("worker", "Fabricator", "hq", [], {
        cost: 45,
        time: 9,
        hp: 35,
        shield: 20,
        shieldRegen: 4,
        speed: 3.3,
        radius: 0.36,
        hover: true,
        inf: true,
        note: "Builds, repairs and mines Aether. Shielded.",
      }),
      trooper: U("trooper", "Sentinel", "barracks", [], {
        cost: 62,
        time: 12,
        hp: 50,
        shield: 32,
        shieldRegen: 6,
        speed: 3.2,
        inf: true,
        hover: true,
        weapons: [
          W({
            name: "Ion Carbine",
            kind: "energy",
            dmg: 8,
            pen: 1,
            range: 7.5,
            cd: 0.9,
            vs: { structure: 0.5 },
          }),
        ],
        strong: "Sustained fights; shields recharge",
        weak: "Energy shots are light vs armor; cannot hit air",
        note: "Energy weapons that cannot target air. Shield recharges after 5s without damage. Priced at a premium (62) for the regenerating hover shield.",
      }),
      raider: U("raider", "Glider", "barracks", [], {
        cost: 74,
        time: 14,
        hp: 45,
        shield: 25,
        shieldRegen: 6,
        atype: "medium",
        speed: 5.6,
        sight: 13,
        radius: 0.45,
        hover: true,
        weapons: [
          W({
            name: "Skimmer Bolt",
            kind: "energy",
            dmg: 5,
            pen: 1,
            range: 6,
            cd: 0.5,
            vs: { structure: 0.5 },
          }),
        ],
        strong: "Scouting, harassment",
        weak: "Anything armored or ranged",
        note: "Fast hover skimmer.",
      }),
      lancer: U("lancer", "Piercer", "barracks", [], {
        cost: 80,
        time: 16,
        hp: 50,
        shield: 25,
        shieldRegen: 6,
        speed: 3,
        inf: true,
        hover: true,
        weapons: [
          W({
            name: "Piercing Lance",
            kind: "lance",
            dmg: 38,
            pen: 10,
            range: 9,
            cd: 2.4,
          }),
        ],
        strong: "Mechs, heavies",
        weak: "Rifle infantry, raiders; cannot hit air",
        note: "Longest-range anti-armor. Ground only.",
      }),
      skyhunter: U("skyhunter", "Arc Pylon", "barracks", [], {
        cost: 80,
        time: 15,
        hp: 55,
        shield: 20,
        shieldRegen: 6,
        speed: 3,
        inf: true,
        hover: true,
        weapons: [
          W({
            name: "Arc Discharge",
            kind: "arc",
            dmg: 14,
            pen: 3,
            range: 10,
            cd: 0.9,
            air: true,
            ground: false,
          }),
        ],
        strong: "All flyers",
        weak: "Cannot attack ground",
        note: "Energy arcs that hit air only.",
      }),
      walker: U("walker", "Warden", "factory", [], {
        cost: 220,
        time: 32,
        supply: 3,
        hp: 190,
        shield: 90,
        shieldRegen: 8,
        armor: 5,
        atype: "heavy",
        speed: 3,
        radius: 0.85,
        hover: true,
        sight: 11,
        weapons: [
          W({
            name: "Warden Beam",
            kind: "energy",
            dmg: 22,
            pen: 5,
            range: 8.5,
            cd: 1.3,
          }),
        ],
        strong: "Infantry, raiders",
        weak: "Piercers and artillery; cannot hit air",
        note: "Hover tank: 190 hp plus a 90-point regenerating shield, armor 5.",
      }),
      artillery: U("artillery", "Prism Cannon", "factory", ["lab"], {
        cost: 195,
        time: 30,
        supply: 3,
        hp: 85,
        shield: 40,
        shieldRegen: 8,
        armor: 1,
        atype: "medium",
        speed: 2.4,
        radius: 0.7,
        hover: true,
        weapons: [
          W({
            name: "Prism Beam",
            kind: "plasma",
            dmg: 36,
            pen: 4,
            range: 19,
            min: 6,
            cd: 4,
            splash: 2,
            delay: 1.5,
          }),
        ],
        strong: "Structures, clumps",
        weak: "Raiders and flyers",
        note: "Range 19, min 6, shells take 1.5s to land, so movers dodge them.",
      }),
      flyer: U("flyer", "Halo", "airfield", [], {
        cost: 210,
        time: 32,
        supply: 3,
        hp: 105,
        shield: 45,
        shieldRegen: 8,
        armor: 1,
        atype: "air",
        speed: 5,
        radius: 0.65,
        air: true,
        sight: 11,
        weapons: [
          W({
            name: "Halo Beams",
            kind: "beam",
            dmg: 9,
            pen: 3,
            range: 8,
            cd: 0.8,
            air: true,
            ground: true,
          }),
        ],
        strong: "Air-to-air, skirmishing",
        weak: "Arc Pylons, AA coils",
        note: "Flying; beams can hit both air and ground.",
      }),
      support: U("support", "Weaver", "barracks", ["lab"], {
        cost: 70,
        time: 14,
        hp: 55,
        shield: 30,
        shieldRegen: 6,
        speed: 3.2,
        hover: true,
        heal: { rate: 4, range: 6, aura: false, shield: 14 },
        weapons: [],
        strong: "Restores shields fast",
        weak: "Unarmed",
        note: "Recharges shields (14/s) and heals hull (4/s) on one ally.",
      }),
      heavy: U("heavy", "Monolith", "factory", ["lab"], {
        cost: 430,
        time: 52,
        supply: 6,
        hp: 480,
        shield: 260,
        shieldRegen: 10,
        armor: 7,
        atype: "heavy",
        speed: 2.3,
        radius: 1.2,
        hover: true,
        sight: 12,
        weapons: [
          W({
            name: "Monolith Beam",
            kind: "energy",
            dmg: 30,
            pen: 7,
            range: 10.5,
            cd: 1.1,
          }),
        ],
        strong: "Sustained ground fights",
        weak: "Piercers, air, artillery; cannot hit air",
        note: "Enormous regenerating shield. Ground only.",
      }),
    },
    buildings: buildings(
      {
        hq: "Core Nexus",
        supply: "Power Obelisk",
        dropoff: "Harvester Spire",
        barracks: "Assembler",
        factory: "Forge Vault",
        airfield: "Levitation Pad",
        lab: "Archive",
        turret: "Beam Pylon",
        aaturret: "Arc Coil",
      },
      {
        cost: 1.0,
        hp: 1,
        time: 1,
        turretW: {
          name: "Pylon Beam",
          kind: "energy",
          dmg: 14,
          pen: 3,
          range: 9,
          cd: 1,
        },
        aaW: {
          name: "Arc Coil",
          kind: "arc",
          dmg: 15,
          pen: 4,
          range: 11,
          cd: 1.1,
          air: true,
          ground: false,
        },
      },
    ),
    upgrades: UPG({
      name: "Phase Cores",
      desc: "Shields +20 and recharge twice as fast.",
      effect: "shield",
    }),
    ability: {
      name: "Aegis Field",
      desc: "Projects an overshield: allies within radius 7 gain +80 shield for 15s. Needs the research building.",
      radius: 7,
      shield: 80,
      delay: 0.3,
      cd: 90,
      target: "ground",
    },
    power: {
      id: "stasis",
      name: "Stasis Bloom",
      short: "Stasis",
      key: "G",
      cost: 90,
      cd: 100,
      delay: 2.5,
      radius: 4.5,
      duration: 3.5,
      target: "ground",
      tint: 0x39e6d6,
      desc: "Seeds a stasis bloom. After a 2.5s telegraph every ENEMY ground unit inside radius 4.5 is frozen for 3.5s: it cannot move or fire, but it is also immune to all damage while frozen. Flyers and structures are unaffected, and your own and allied units are never touched. Costs 90 Aether, cooldown 100s. Needs the research building and a target your team can see. Counterplay: walk out of the ring during the telegraph, keep flyers out of it, and ignore frozen units to kill everything else.",
    },
    mods: { regen: 0, autoGrow: 0, prodTime: 1, buildBonusHp: 1 },
  };

  N.FACTIONS = F;
  N.FACTION_IDS = ["vanguard", "brood", "lattice"];

  // Team / commander presentation. Team colour is the blue/red family; each commander also has a distinct accent so six armies stay readable.
  N.TEAM_NAMES = ["Blue Team", "Red Team"];
  N.TEAM_COLORS = [0x2aa8ff, 0xff3b30];
  N.PLAYER_COLORS = [
    0x2aa8ff, 0x21d3b8, 0x9a7dff, 0xff3b30, 0xff9a1f, 0xff4fb3,
  ];
  N.PLAYER_COLOR_NAMES = [
    "Azure",
    "Teal",
    "Violet",
    "Crimson",
    "Amber",
    "Magenta",
  ];
  N.CAPTURE_GRACE = 3; // seconds a unit must exist before it counts toward capturing anything (no capture-by-spawn)

  // Strategic sites: mechanically different benefits for the team that HOLDS them. All benefits are recomputed from current ownership every tick.
  N.SITES = {
    radar: {
      name: "Recon Array",
      icon: "RA",
      capR: 6,
      capTime: 12,
      vision: 20,
      tint: 0x66d9ff,
      desc: "Holding team: shared, real vision in radius 20 around the array (units there can be seen and targeted by anyone on your team who has range). Vision follows ownership: lost on capture, granted to the new holder.",
    },
    foundry: {
      name: "Repair Foundry",
      icon: "RF",
      capR: 6,
      capTime: 12,
      radius: 9,
      rate: 7,
      shield: 5,
      tint: 0x7dff9a,
      desc: "Holding team: friendly units within 9 tiles regain 7 hp/s (and 5 shield/s). Free, units only, never heals the enemy; stops the moment you lose the site.",
    },
    nexus: {
      name: "Transit Nexus",
      icon: "TN",
      capR: 6,
      capTime: 14,
      radius: 8,
      costPerSupply: 12,
      channel: 3,
      cooldown: 30,
      maxUnits: 12,
      tint: 0xd18cff,
      desc: "Holding team: select units within 8 tiles of a held Nexus and send them to another Nexus your team also holds. Costs 12 Aether per supply moved, takes a 3s channel (units are stationary and vulnerable; losing either Nexus cancels and refunds), then a 30s cooldown on the departure Nexus. Max 12 units per trip.",
    },
  };
  N.SITE_KINDS = ["radar", "foundry", "nexus"];
  N.DIFFICULTY = {
    easy: {
      label: "Easy",
      think: 40,
      gather: 0.8,
      workers: 10,
      wave: 26,
      waveMin: 16,
      note: "Slower reactions, 20% slower gathering, smaller waves.",
    },
    normal: {
      label: "Normal",
      think: 20,
      gather: 1.0,
      workers: 16,
      wave: 18,
      waveMin: 10,
      note: "Same rules and economy as you. No bonuses.",
    },
    hard: {
      label: "Hard",
      think: 12,
      gather: 1.25,
      workers: 20,
      wave: 12,
      waveMin: 6,
      note: "Faster decisions, earlier attacks and a disclosed +25% Aether from each delivery.",
    },
  };

  N.unitDef = (fid, role) => F[fid].units[role];
  N.buildingDef = (fid, role) => F[fid].buildings[role];
  N.defOf = (fid, role) => F[fid].units[role] || F[fid].buildings[role];
  N.isEnumKey = (obj, k) =>
    typeof k === "string" && Object.prototype.hasOwnProperty.call(obj, k);
  N.weaponHits = function (w, targetAir) {
    // The one rule for "can this weapon damage that category?" Used for targeting AND damage application.
    if (targetAir) return !!w.air && N.NO_AIR.indexOf(w.kind) < 0;
    return !!w.ground;
  };
})();
